version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 212914134641.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI_WORDPRESS=212914134641.dkr.ecr.eu-south-1.amazonaws.com/ecrwordpress
      - REPOSITORY_URI_APACHE=212914134641.dkr.ecr.eu-south-1.amazonaws.com/ecrapache
  build:
    commands:
      - echo Building apache Docker image...
      - docker build -f Dockerfile.apache -t apache-image .
      - echo Building wordpress Docker image...
      - docker build -f Dockerfile.wordpress -t wordpress-image . 
  post_build:
    commands:
      - docker tag wordpress-image:latest $REPOSITORY_URI_WORDPRESS:latest
      - docker push $REPOSITORY_URI_WORDPRESS:latest
      - docker tag apache-image:latest $REPOSITORY_URI_APACHE:latest
      - docker push $REPOSITORY_URI_APACHE:latest
      - echo Build and push completed on `date`
      - aws cloudformation create-stack --stack-name Auto-Infrastracture --template-body file://infrastracture/ec2.yaml --parameters file://infrastracture/ec2.json --capabilities "CAPABILITY_AUTO_EXPAND" "CAPABILITY_NAMED_IAM" "CAPABILITY_IAM"
      - aws cloudformation wait stack-create-complete --stack-name Auto-Infrastracture
